FROM node:12
MAINTAINER Chris Lanus <cqlanus@gmail.com>

# set working directory
WORKDIR /app

RUN npm install sequelize-cli pg pg-hstore sequelize

COPY package.json ./
COPY config/ ./config
COPY migrations/ ./migrations
COPY seeders/ ./seeders
COPY models/ ./models
COPY db/ ./db
COPY scripts/ ./scriptseders/ models/ db/ scripts/ ./

EXPOSE 8000

CMD sh scripts/bootstrap.sh
