version: "3"
services:
  api:
    image: node:12
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "9001:9001"
    environment:
      - PORT=9001
      - POSTGRES_USER=clanus
      - POSTGRES_DB=MLID

    restart: always
    command: sh -c "npm install && npm run db:create && npm run db:seed && npm run dev"

  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
     POSTGRES_USER: "clanus"
     POSTGRES_DB: "MLID"

volumes:
  postgres-data:
