version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "9001:9001"
    restart: always
    volumes:
      - .:/app
    environment:
      WAIT_HOSTS: postgres:5432

  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
     POSTGRES_USER: "postgres"
     POSTGRES_DB: "MLID"

volumes:
  postgres-data:
