FROM node:12
MAINTAINER Chris Lanus <cqlanus@gmail.com>

# set working directory
WORKDIR /app

RUN npm install sequelize-cli pg pg-hstore sequelize

COPY package.json ./
COPY config/ ./config
COPY migrations/ ./migrations
COPY seeders/ ./seeders
COPY models/ ./models
COPY db/ ./db
COPY scripts/ ./scripts
COPY lib/ ./lib
COPY station_mlid.json ./

EXPOSE 8000

CMD /bin/sh ./scripts/run_db_job.sh
