apiVersion: batch/v1
kind: Job
metadata:
  name: lan-wx-db-job
  namespace: lan-wx
spec:
  template:
    spec:
      containers:
      - name: lan-wx-db-job
        image: cqlanus/lan-wx-db:latest
        env:
          - name: NODE_ENV
            value: production
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_HOST
            value: lan-wx-redis
        command: [ "/bin/sh", "./scripts/run_db_job.sh" ]
      restartPolicy: Never
  backoffLimit: 4
